<?php
/* ActiveFusions 2015/12/11 18:51 */

namespace Plugin\Holiday\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * HolidayConfig
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayConfigRepository extends EntityRepository{

	/**
	* find month day
	*
	* @return type
	**/
	public function findConfig($id){
		$query = $this->getEntityManager()->createQuery('SELECT m.config_data FROM Plugin\Holiday\Entity\HolidayConfig m WHERE m.id = :id ORDER BY m.id ASC');
		$query->setParameter('id', $id);
		$result = $query->getResult(Query::HYDRATE_ARRAY);
		return $result;
	}

	/**
	* @param  \Plugin\Holiday\Entity\HolidayConfig $HolidayConfig
	* @return bool
	*/
	public function save(\Plugin\Holiday\Entity\HolidayConfig $HolidayConfig){
		$em = $this->getEntityManager();
		$em->getConnection()->beginTransaction();
		try {
			$em->persist($HolidayConfig);
			$em->flush();
			$em->getConnection()->commit();
		} catch (\Exception $e) {
			$em->getConnection()->rollback();
			return false;
		}
		return true;

	}

}
