<?php
namespace Plugin\Holiday\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * HolidayWeek
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayWeekRepository extends EntityRepository{

	/**
	* find month day
	*
	* @param  $id
	* @return type
	**/
	public function findWeek($id){
		$query = $this->getEntityManager()->createQuery('SELECT m.week FROM Plugin\Holiday\Entity\HolidayWeek m WHERE m.id = :id ORDER BY m.id ASC');
		$query->setParameter('id', $id);
		$result = $query->getResult(Query::HYDRATE_ARRAY);
		return $result;
	}

	/**
	* @param  \Plugin\Holiday\Entity\HolidayWeek $HolidayWeek
	* @return bool
	*/
	public function save(\Plugin\Holiday\Entity\HolidayWeek $HolidayWeek){
		$em = $this->getEntityManager();
		$em->getConnection()->beginTransaction();
		try {
			$em->persist($HolidayWeek);
			$em->flush();
			$em->getConnection()->commit();
		} catch (\Exception $e) {
			$em->getConnection()->rollback();
			return false;
		}
		return true;
	}











}
